version: "3.8"

services:
  # Base de données
  articles-db:
    build: ./articles-db
    image: articles-db
    container_name: articles-db
    networks:
      - articles-network
    volumes:
      - articles-db-data:/var/lib/mysql

  # Web API
  articles-back:
    build: ./articles-back
    image: articles-back
    container_name: articles-back
    depends_on:
      - articles-db
    ports:
      - "8000:8080"
    networks:
      - articles-network

  # App Angular
  articles-front:
    build: ./articles-front
    image: articles-front
    container_name: articles-front
    depends_on:
      - articles-db
      - articles-back
    ports:
      - "4000:4200"
    networks:
      - articles-network

networks:
  articles-network:

volumes:
  articles-db-data:
